apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
spec:
  channel: "4.3"
  name: serverless-operator
  source: operators
  sourceNamespace: openshift-operators
